-- ============================================================
-- ERVARIA - Seed: 42 ervas (admin_herbs)
-- ============================================================
-- Rode no Supabase SQL Editor. Se admin_herbs ja tem linhas,
-- este INSERT vai duplicar. Rode so se admin_herbs esta com 0.
--
-- Conteudo extraido de ervaria-seed-data.sql (linhas 14-68)
-- para evitar conflito com INSERTs de admin_products que ja
-- foram rodados.
-- ============================================================

INSERT INTO public.admin_herbs (name, latin_name, icon, category, effects, detail, safe_for, avoid_for, temp, brew_time, dose, frequency, tags, momento) VALUES
('Camomila','Matricaria chamomilla','🌼','Calmante','Calmante suave, anti-inflamatória, digestiva','Apigenina se liga aos receptores GABA, promovendo relaxamento. Ideal para insônia leve, cólicas e digestão irritada. Segura para crianças, idosos e gestantes.','{"gestantes","hipertensos","crianças"}','{}','85°C','8 min','1-2 col. sopa / 250ml','2-3x ao dia','{"calmante","digestiva","anti-inflamatória","sono"}','{"tarde","qualquer"}'),
('Valeriana','Valeriana officinalis','🌸','Sono','Sedativa potente, insônia, ansiedade grave','Actua diretamente no GABA. Reduz tempo para adormecer em 30-60 min. Não associar com álcool ou benzodiazepínicos. Evitar em depressão.','{"hipertensos"}','{"gestantes","antes de dirigir"}','85°C','10 min','1 col. sopa / 250ml','1x à noite','{"sono","ansiedade","sedativa","calmante"}','{"noite"}'),
('Maracujá','Passiflora spp. (P. alata · P. edulis · P. incarnata)','🌿','Calmante','Ansiolítico — ação monografada, Sedativo leve, Indutor suave de sono','Três espécies oficiais brasileiras com farmacologia GABAérgica. Flavonoides (vitexina, isovitexina) se ligam ao receptor GABA-A com afinidade baixa, produzindo calma sem sedação pesada. Monografia oficial da Farmacopeia Brasileira.','{"adultos saudáveis","hipertensos"}','{}','95°C','10 min','3 g de folhas secas (partes aéreas para P. incarnata) para 150 ml','Fim de tarde e noite. 2 a 4 vezes ao dia conforme monografia.','{"ansiedade","sono"}','{"tarde","noite"}'),
('Melissa','Melissa officinalis','🍃','Calmante','Calmante, antidepressiva suave, digestiva','Inibe MAO-B, elevando serotonina e dopamina naturalmente. Excelente para quem não consegue parar de pensar. Sabor agradável de limão. Sem risco de dependência.','{"gestantes","crianças","hipertensos"}','{}','85°C','7 min','1-2 col. sopa / 250ml','3x ao dia','{"ansiedade","digestiva","calmante","antidepressiva"}','{"tarde","noite","qualquer"}'),
('Gengibre','Zingiber officinale','🫚','Digestivo','Anti-náusea, digestivo, termogênico, antigripal','Procinético: acelera esvaziamento gástrico. Anti-inflamatório que inibe COX-2 e LOX. Eficaz quanto ibuprofeno para dor menstrual em estudos.','{"hipertensos"}','{"gestantes (doses altas)","anticoagulantes"}','90°C','10 min','3-4 fatias frescas / 300ml','conforme necessidade','{"digestivo","náusea","inflamação","termogênico","gripe"}','{"manha","qualquer"}'),
('Chá Verde','Camellia sinensis','🍵','Estimulante','Foco, antioxidante, termogênico, metabolismo','L-teanina + cafeína: estado único de foco calmo. EGCG: antioxidante mais estudado do mundo. Tomar 30min antes de exercício potencializa queima de gordura.','{}','{"gestantes","insônia","hipertensos sensíveis","após 16h"}','75°C','3-4 min','1 col. sopa / 200ml','1-2x manhã','{"foco","energia","metabolismo","antioxidante"}','{"manha","tarde"}'),
('Hibisco','Hibiscus sabdariffa','🌺','Cardiovascular','Hipotensor, antioxidante, emagrecimento, vitamina C','Estudo JAMA: 3 xícaras/dia reduziram PA sistólica em média 7mmHg. Rico em antocianinas. Inibe amilase, reduzindo absorção de carboidratos.','{}','{"gestantes","pressão baixa","uso com diuréticos"}','90°C','8 min','2 col. sopa / 300ml','2-3x ao dia','{"pressão","antioxidante","emagrecimento","vitamina C"}','{"qualquer"}'),
('Alecrim','Rosmarinus officinalis','🌿','Estimulante','Foco, memória, circulação, estimulante','1,8-cineol no aroma já melhora desempenho cognitivo. Estimula circulação cerebral e periférica. Excelente para manhãs lentas e concentração. Sem cafeína.','{"hipertensos"}','{"gestantes (doses altas)","epilepsia"}','90°C','5 min','1 col. sopa / 200ml','1-2x ao dia','{"foco","memória","energia","circulação"}','{"manha","tarde"}'),
('Hortelã','Mentha piperita','🌿','Digestivo','Digestiva, carminativa, descongestionante, fresca','Mentol relaxa musculatura lisa intestinal. Alivia IBS em estudos clínicos. Descongestionante das vias aéreas.','{"hipertensos","crianças (sem óleo essencial)"}','{"gestantes (doses altas)","bebês (óleo)","refluxo grave"}','85°C','5 min','1 col. sopa / 250ml','após refeições','{"digestivo","gases","congestão","frescor"}','{"qualquer"}'),
('Erva-doce','Pimpinella anisum','🌾','Digestivo','Carminativa, antigases, cólicas, expectorante','Carminativo clássico: relaxa musculatura intestinal e libera gases. Seguro até para bebês (muito diluído). Combina muito bem com camomila e hortelã.','{"hipertensos","crianças","gestantes (uso moderado)"}','{}','90°C','7 min','1 col. sopa / 250ml','após refeições','{"gases","cólicas","digestivo","expectorante"}','{"qualquer"}'),
('Canela','Cinnamomum zeylanicum','🌿','Metabólico','Termogênica, regula glicemia, anti-inflamatória','Regula insulina, evita pico glicêmico. Termogênica e adocicada: reduz desejo por doces. Cassia tem cumarina (limitar). Prefira canela-do-ceilão.','{"hipertensos"}','{"gestantes (doses altas)","anticoagulantes"}','95°C','10 min','1 pau ou 1 col. / 300ml','2x ao dia','{"metabolismo","glicemia","termogênico","digestivo"}','{"manha","tarde"}'),
('Cúrcuma','Curcuma longa','🫚','Anti-inflamatório','Anti-inflamatório potente, hepático, antioxidante','Curcumina: inibe COX-2. Eficaz quanto ibuprofeno em artrite em estudos. Adicionar pimenta-do-reino aumenta absorção em 2000%.','{"hipertensos"}','{"gestantes (doses altas)","pedras na vesícula","anticoagulantes"}','90°C','10 min','1 col. chá + pitada pimenta / 250ml','2x ao dia','{"anti-inflamatório","fígado","articulações","antioxidante"}','{"qualquer"}'),
('Alfazema','Lavandula angustifolia','💜','Calmante','Ansiolítica, sedativa suave, dor de cabeça','Estudo Lasea: eficaz quanto lorazepam para ansiedade leve. Reduz ondas beta cerebrais. Aroma + infusão combinados têm efeito sinérgico.','{"hipertensos"}','{"gestantes"}','85°C','8 min','1 col. sopa flores / 250ml','2x ao dia','{"ansiedade","sono","dor de cabeça","calmante"}','{"tarde","noite"}'),
('Boldo','Peumus boldus','🍃','Digestivo','Hepático, digestivo, alivia peso pós-refeição','Colagogo clássico: estimula produção e fluxo de bile. Alivia sensação de peso em 20-30 min. Não usar por mais de 6 semanas seguidas.','{"hipertensos"}','{"gestantes","obstrução biliar","uso prolongado"}','90°C','5 min','1 col. sopa / 250ml','após refeição gordurosa','{"fígado","digestivo","bile","ressaca"}','{"qualquer"}'),
('Alcachofra','Cynara scolymus','🌱','Digestivo','Detox fígado, reduz colesterol, diurética','Cinarina: aumenta produção de bile. Colerético + detox suave e progressivo. Combina com boldo para digestão pesada.','{"hipertensos"}','{"gestantes","obstrução biliar","alergia a asteráceas"}','90°C','10 min','1-2 col. sopa / 300ml','2x ao dia','{"fígado","colesterol","digestivo","detox"}','{"qualquer"}'),
('Guaco','Mikania glomerata','🍃','Respiratório','Broncodilatador, expectorante, tosse, gripe','Regulamentado pela ANVISA como fitoterápico. Broncodilatador natural mais eficaz. Pode ser usado como xarope ou chá.','{"hipertensos"}','{"gestantes","uso prolongado sem supervisão"}','90°C','10 min','2 col. sopa / 300ml','3-4x ao dia (gripe)','{"tosse","bronquite","gripe","expectorante"}','{"qualquer"}'),
('Capim-Limão','Cymbopogon citratus','🌾','Calmante','Calmante, digestivo, antigripal, febre','Sabor cítrico agradável. Calmante sem sonolência intensa. Antipirético e antigripal suave. Muito consumido no Brasil.','{"gestantes","hipertensos","crianças"}','{}','90°C','8 min','2-3 folhas frescas / 300ml','3x ao dia','{"calmante","febre","digestivo","cítrico"}','{"qualquer"}'),
('Folha de Amora','Morus nigra','🍃','Hormonal','Menopausa, suores noturnos, fitoestrogênios','Fitoestrogênios reduzem sintomas da menopausa. Estudo: reduz calores em 50% em 8 semanas. Hipoglicemiante suave.','{"hipertensos"}','{"gestantes","câncer hormônio-dependente"}','88°C','10 min','1-2 col. sopa / 250ml','2x ao dia','{"menopausa","hormônios","fitoestrogênio","hipoglicemiante"}','{"tarde","noite"}'),
('Erva Cidreira','Lippia alba','🍃','Calmante','Calmante suave, digestiva, ansiedade','Calmante brasileiro clássico. Suave e seguro para toda a família. Ideal para estresse diário leve sem causar sedação.','{"gestantes","crianças","hipertensos"}','{}','85°C','7 min','1-2 col. sopa / 250ml','3x ao dia','{"calmante","ansiedade","digestivo","família"}','{"tarde","noite","qualquer"}'),
('Espinheira Santa','Maytenus ilicifolia','🌿','Digestivo','Gastrite, úlcera, acidez, antiácido natural','Antiácido e cicatrizante natural da mucosa gástrica. Regulado pela ANVISA. Tomar em jejum e antes das refeições.','{"hipertensos"}','{"gestantes","amamentação"}','88°C','10 min','1 col. sopa / 250ml','3x ao dia em jejum','{"gastrite","úlcera","acidez","estômago"}','{"qualquer"}'),
('Carqueja','Baccharis trimera','🌿','Metabólico','Termogênica, digestiva, saciedade, diabetes','Termogênica e reduz absorção de gordura. Auxiliar no emagrecimento. Amargo: combinar com canela para suavizar.','{"hipertensos"}','{"gestantes"}','90°C','8 min','1 col. sopa / 250ml','antes das refeições','{"emagrecimento","termogênico","diabetes","fígado"}','{"manha","tarde"}'),
('Ginkgo Biloba','Ginkgo biloba','🍃','Cognitivo','Memória, circulação cerebral, concentração','Aumenta fluxo sanguíneo cerebral. Resultados em 4-6 semanas de uso contínuo. Evitar com anticoagulantes.','{"hipertensos"}','{"gestantes","anticoagulantes","antes de cirurgia"}','90°C','10 min','1 col. sopa / 250ml','2x ao dia','{"memória","foco","circulação","cognitivo"}','{"manha","tarde"}'),
('Hibisco Azul','Clitoria ternatea','💙','Cognitivo','Antioxidante, memória, ansiedade, muda de cor','Muda de roxo para rosa/vermelho com limão (antocianinas sensíveis ao pH). Antioxidante cerebral. Estudos mostram melhora em testes cognitivos.','{"hipertensos"}','{"gestantes"}','90°C','5 min','1-2 col. sopa / 250ml','1-2x ao dia','{"cognitivo","antioxidante","memória","beleza"}','{"tarde","qualquer"}'),
('Calêndula','Calendula officinalis','🌸','Pele','Cicatrizante, anti-inflamatória, antifúngica','Cicatrizante interno e externo. Anti-inflamatória da mucosa e pele. Usar também como compressa.','{"hipertensos"}','{"gestantes","alergia a asteráceas"}','88°C','8 min','1-2 col. sopa flores / 250ml','2-3x ao dia','{"pele","cicatrizante","anti-inflamatório","gastrite"}','{"qualquer"}'),
('Rooibos','Aspalathus linearis','🍃','Antioxidante','Antioxidante potente, sem cafeína, anti-aging','Antioxidante 50x mais potente que chá verde segundo alguns estudos. Sem cafeína: ideal à tarde e noite. Rico em minerais.','{"gestantes","crianças","hipertensos"}','{}','95°C','5-7 min','1-2 col. sopa / 300ml','a qualquer hora','{"antioxidante","sem cafeína","anti-aging","pele"}','{"tarde","noite","qualquer"}'),
('Ashwagandha','Withania somnifera','🌿','Adaptogênico','Reduz cortisol, estresse, energia, libido','Reduce cortisol em até 30% em estudos. Adaptogênico: acalma sob estresse, energiza sob fadiga. Resultados em 4-8 semanas.','{"hipertensos"}','{"gestantes","hipertireoidismo","doenças autoimunes"}','90°C','10 min','1 col. chá pó / 250ml','2x ao dia','{"adaptogênico","estresse","cortisol","libido"}','{"tarde","noite"}'),
('Guaraná','Paullinia cupana','🫐','Estimulante','Estimulante, foco, metabolismo, emagrecimento','Cafeína de liberação mais lenta que o café. Menos pico e queda. Rico em taninos e guaranina.','{}','{"gestantes","hipertensos","insônia","crianças","após 15h"}','85°C','5 min','1/2 col. chá pó / 250ml','1x manhã','{"energia","foco","metabolismo","estimulante"}','{"manha"}'),
('Tomilho','Thymus vulgaris','🌿','Respiratório','Expectorante, antisséptico, tosse, bronquite','Timol: antisséptico pulmonar potente. Usado como xarope na Europa há séculos. Dissolve muco e desinfeta vias aéreas.','{"hipertensos"}','{"gestantes (doses altas)"}','90°C','8 min','1 col. sopa / 250ml','3x ao dia','{"tosse","expectorante","bronquite","antisséptico"}','{"qualquer"}');

-- ═══ 14 ERVAS BRASILEIRAS NOVAS (ids 29-42 em app.js) ═══
-- INSERT separado por incluir colunas linha/tagline (adicionadas depois da base).
-- Fontes: monografias Farmacopeia Brasileira + Formulario de Fitoterapicos (Anvisa, 2011).

INSERT INTO public.admin_herbs (name, latin_name, icon, category, linha, tagline, effects, detail, safe_for, avoid_for, temp, brew_time, dose, frequency, tags, momento) VALUES
('Aroeira-da-Praia','Schinus terebinthifolius Raddi','🌿','Anti-inflamatório','Funcional','Pimenta-rosa brasileira virou cicatrizante ginecológico oficial.','Anti-inflamatório tópico — monografado, Cicatrizante ginecológico, Adstringente potente','Planta caiçara com dupla identidade: tempero gourmet (pimenta-rosa) e fitoterápico monografado. Casca em decocção para uso externo ginecológico — anti-inflamatório e cicatrizante via taninos concentrados.','{"adultos saudáveis","hipertensos"}','{}','100°C','10 min','1 g de cascas secas / 150 ml (uso externo)','banho de assento 3-4x ao dia','{"inflamacao","pele","ginecologico","oral"}','{"qualquer"}'),
('Assa-Peixe','Vernonia polyanthes Less','🌿','Respiratório','Essencial','Arbusto de pastagens brasileiras — expectorante oficial da Anvisa.','Expectorante — monografado, Anti-inflamatório, Broncodilatador leve','Arbusto pioneiro de pastagens brasileiras. Expectorante monografado pela Anvisa — saponinas estimulam secreção brônquica. Flor importante para apicultura nacional.','{"adultos saudáveis","hipertensos"}','{"gestantes","lactantes"}','95°C','10 min','3 g de folhas secas / 150 ml','1x ao dia em quadros agudos','{"respiratorio"}','{"qualquer"}'),
('Barbatimão','Stryphnodendron adstringens (Mart.) Coville','🌿','Pele','Funcional','Árvore do cerrado com casca cicatrizante oficial da Anvisa.','Cicatrizante — monografado, Adstringente potente, Anti-inflamatório tópico','Árvore do cerrado com a maior concentração de taninos condensados entre as ervas oficiais brasileiras. Creme cicatrizante monografado — taninos formam película proteica sobre feridas. Uso externo.','{"adultos saudáveis","hipertensos"}','{}','95°C','10 min','Creme: aplicação tópica conforme bula','2-3x ao dia','{"inflamacao","pele","ginecologico","oral"}','{"qualquer"}'),
('Boldo-Baiano','Vernonia condensata Baker','🌿','Digestivo','Essencial','O terceiro boldo brasileiro — folha amarga do quintal nordestino.','Antidispéptico, Hepatoativo leve, Anti-inflamatório leve','Terceira planta brasileira chamada boldo — folha amarga com sesquiterpenos lactonas. Antidispéptico monografado. Tradição afro-brasileira no Nordeste.','{"adultos saudáveis","hipertensos"}','{}','95°C','10 min','conforme monografia oficial','após refeições','{"digestao"}','{"qualquer"}'),
('Boldo-Brasileiro','Plectranthus barbatus Andrews','🌿','Digestivo','Essencial','O boldo do quintal brasileiro — planta africana naturalizada, gentil.','Antidispéptico — monografado, Colagogo leve, Hepatoativo suave','Planta africana (Plectranthus barbatus) naturalizada nos quintais brasileiros. Antidispéptico monografado, mais gentil que o boldo-do-chile. Forskolina é seu diterpeno característico.','{"adultos saudáveis"}','{"gestantes","lactantes","crianças","hipertensos"}','95°C','5 min','1 a 3 g de folhas / 150 ml (1 a 3 folhas frescas)','2-3x ao dia após refeições pesadas','{"digestao","hepatico"}','{"qualquer"}'),
('Chambá','Justicia pectoralis Jacq.','🌿','Respiratório','Essencial','Erva do Nordeste com aroma de baunilha e ação expectorante oficial.','Expectorante — monografado, Broncodilatador leve, Antitussígeno suave','Erva do Ceará com aroma de baunilha (cumarina). Expectorante monografado, permitido a partir dos 3 anos. Base do programa Farmácias Vivas da UFC.','{"adultos saudáveis","hipertensos"}','{"anticoagulantes"}','95°C','10 min','5 g de partes aéreas / 150 ml','2-3x ao dia em quadros de tosse','{"respiratorio","inflamacao"}','{"qualquer"}'),
('Chapéu-de-Couro','Echinodorus macrophyllus (Kunth) Micheli','🌿','Urinário','Funcional','Folha larga de brejo brasileiro — diurético e anti-inflamatório oficial.','Diurético leve — monografado, Anti-inflamatório — monografado, Antidispéptico','Folha larga de brejos brasileiros. Diurético e anti-inflamatório monografado — diterpenos clerodanos. Uso tradicional em litíase urinária e gota.','{"adultos saudáveis"}','{"gestantes","lactantes","hipertensos"}','95°C','10 min','1 g de folhas / 150 ml','3x ao dia antes das refeições','{"urinario"}','{"qualquer"}'),
('Copaíba','Copaifera spp. (C. langsdorffii · C. multijuga · C. reticulata)','🌿','Anti-inflamatório','Funcional','Óleo-resina do coração da Amazônia — anti-inflamatório tópico poderoso.','Anti-inflamatório tópico — monografado, Cicatrizante, Antimicrobiano','Óleo-resina extraído do tronco de árvores amazônicas centenárias. Pomada anti-inflamatória monografada — beta-cariofileno age no receptor canabinoide CB2. Três espécies oficiais.','{"adultos saudáveis","hipertensos"}','{}','95°C','10 min','Pomada: aplicação tópica conforme bula','2-3x ao dia em área afetada','{"inflamacao","pele"}','{"qualquer"}'),
('Erva-Baleeira','Cordia verbenacea DC.','🌿','Anti-inflamatório','Funcional','Do litoral atlântico ao primeiro fitoterápico brasileiro patenteado (Acheflan).','Anti-inflamatório tópico — monografado, Analgésico local, Antimicrobiano tópico','Planta caiçara do litoral atlântico. Primeiro fitoterápico brasileiro com pesquisa clínica completa (Acheflan). Anti-inflamatório tópico via alfa-humuleno e trans-cariofileno.','{"adultos saudáveis","hipertensos"}','{}','95°C','10 min','3 g de folhas / 150 ml (uso externo)','compressa 3x ao dia','{"inflamacao"}','{"qualquer"}'),
('Erva-de-Bicho','Polygonum punctatum Elliot','🌿','Anti-inflamatório','Funcional','Pimenteira-d''água das várzeas brasileiras — anti-hemorroidal oficial.','Anti-hemorroidal — monografado, Adstringente (taninos), Hemostático local','Planta de várzeas brasileiras com sabor picante (polygodial). Anti-hemorroidal monografado — banho de assento. Taninos adstringentes mais leve irritação local produzem efeito contração-cicatrização.','{"adultos saudáveis","hipertensos"}','{"gestantes","lactantes"}','95°C','10 min','3 g de partes aéreas / 150 ml (uso externo)','banho de assento 3x ao dia','{"hemorroidas"}','{"qualquer"}'),
('Erva-Mate','Ilex paraguariensis A.St.-Hil.','🧉','Estimulante','Essencial','Chimarrão, tererê e chá-mate — estímulo brasileiro por excelência.','Estimulante, Antioxidante, Termogênico, Diurético leve','Xantinas (cafeína mais teobromina) e polifenóis. Ritual comunitário do Sul. Consumo muito quente associado a câncer de esôfago (IARC 2A) — evitar acima de 70°C.','{"hipertensos (moderado)"}','{"gestantes","insônia","crianças","após 16h"}','70°C','4 min','1 col. sopa / 200ml','manhã-tarde','{"energia","foco","termogênico","antioxidante","tradição"}','{"manha","tarde"}'),
('Guaçatonga','Casearia sylvestris Sw.','🌿','Digestivo','Essencial','Erva-de-bugre da Mata Atlântica — antiulcerosa nativa brasileira.','Antidispéptico — monografado, Antiulcerogênico, Anti-inflamatório','Irmã menos famosa da espinheira-santa — antidispéptico e antiulcerogênico monografado. Casearinas (diterpenos clerodanos) com atividade antitumoral em estudos de bancada.','{"adultos saudáveis","hipertensos"}','{"gestantes","lactantes","crianças"}','95°C','5 min','2 a 4 g de folhas / 150 ml','2-3x ao dia antes das refeições','{"digestao","inflamacao","oral"}','{"qualquer"}'),
('Macela','Achyrocline satureioides (Lam.) DC.','🌿','Digestivo','Essencial','Flor amarela do pampa — tradição gaúcha de colher na Sexta-Feira Santa.','Antidispéptico — monografado, Antiespasmódico digestivo, Anti-inflamatório','Flor amarela do pampa, tradição gaúcha colher na Sexta-Feira Santa. Antidispéptico monografado — flavonoides com ação antiespasmódica e ansiolítica leve. Travesseiros aromáticos do Sul.','{"adultos saudáveis","hipertensos"}','{"gestantes","crianças"}','95°C','5 min','1,5 g de sumidades floridas / 150 ml','2-3x ao dia após refeições','{"digestao","inflamacao","antiespasmodico"}','{"noite"}'),
('Quebra-Pedra','Phyllanthus niruri L.','🌿','Urinário','Funcional','A erva que dissolve cálculos renais — litolítico oficial da Anvisa.','Litolítico — monografado, Diurético leve, Anti-inflamatório','Erva rasteira que reduz formação de cristais urinários. Litolítico monografado pela Anvisa — lignanas (filantina, hipofilantina) previnem nucleação de oxalato de cálcio. Manter hidratação.','{"adultos saudáveis","hipertensos"}','{"gestantes"}','95°C','10 min','3 g de partes aéreas / 150 ml','2-3x ao dia','{"urinario"}','{"qualquer"}');

-- Preenche linha/tagline do Maracuja (row atualizada no INSERT 1 sem essas colunas).
UPDATE public.admin_herbs
SET linha = 'Essencial',
    tagline = 'Três espécies oficiais brasileiras, uma farmacologia GABAérgica — ansiolítico popular com evidência clínica robusta.'
WHERE name = 'Maracujá'

-- ============================================================
-- Verificacao
-- ============================================================
SELECT count(*) AS total_ervas FROM public.admin_herbs;
